import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "my website",
  description: "Generated by create next app",
};

export default function loginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <h1>kosong</h1>
        {children}
        <h1>kosong</h1>
        
        </body>
    </html>
  );
}
